In [1]:
categories = ["entertainment", "sports", "technology", "politics","health", "business", "science"]
#categories = ["entertainment", "sports", "technology", "politics"]
type(categories)

list

In [10]:
cat_list = []
data_list = []
for cat in categories:
    #print(cat)
    with open('{}.txt'.format(cat), encoding='utf-8') as f:
    #lines = [line.rstrip('\n') for line in open('{}.txt'.format(cat))]
        lines=f.readlines()
        print(cat + " " + str(len(lines)))
        lines = [x.strip() for x in lines]
        data_list.extend(lines)
        le = len(lines)
        for r in range(le):
            cat_list.append(cat)

entertainment 601
sports 608
technology 614
politics 622
health 329
business 346
science 337


In [11]:
print(len(data_list))
#print(data_list)
print(len(cat_list))
#print(cat_list)

3457
3457


In [12]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
target = le.fit_transform(cat_list)
print(len(target))
print(target)

3457
[1 1 1 ... 4 4 4]


In [13]:
#TESTING

import pandas as pd
d = {'Headlines':data_list, 'Category':cat_list, 'Target': target}
#print(d)
df = pd.DataFrame(d)
print(df.iloc[2600])

Headlines    Here we tell you how you can prevent antimicro...
Category                                                health
Target                                                       2
Name: 2600, dtype: object


In [14]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
x_train_tf = count_vect.fit_transform(data_list)
print(type(data_list))
print(x_train_tf.shape)
print(x_train_tf.toarray())

<class 'list'>
(3457, 12673)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [15]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
x_train_tfidf = tfidf_transformer.fit_transform(x_train_tf)
x_train_tfidf.shape

(3457, 12673)

In [16]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(x_train_tfidf, target)

In [17]:
print(categories)
print(target)

['entertainment', 'sports', 'technology', 'politics', 'health', 'business', 'science']
[1 1 1 ... 4 4 4]


In [44]:
test_data = []
with open('headlines.txt', 'r+', encoding='utf-8') as f:
    lines = f.readlines()
    lines = [x.strip() for x in lines]
    test_data.extend(lines)
print(len(test_data))

50


In [45]:
#test_data = ["The value of losses from crime in the digital currency sector in 2018 hit $1.7 billion.", "15 jawans killed after Naxals trigger IED blast in Maharashtra's Gadchiroli.",  "iPhone XS specs vs. XS Max, XR, X: What's the same and different", "2 People Injured In Indiana School Shooting", "Twitter Bots May Have Delivered Donald Trump's Victory, Research Paper Says", "60 Seconds of Social Media", "My Son Only Read One Book in Middle School"]
#test_data = ["Most developers should be familiar with Google's cross-platform, portable UI framework Flutter, which can make developing apps for both Android and iOS a whole lot easier. In fact, it just recently hit 1.0 late last year. Today, at the company's I/O developer"]
#test_data=["How the battle against measles varies around the world", "Shy fish no bigger than a pinkie provide much of the food in coral reefs", "BJP wants to piggyback on YSRCP to south, but Jagan may find it hard to help without special status for Andhra", "FDA Approves New Treatment for Diabetic Condition That Can Lead to Blindness","Welspun in talks to own slum rehabilitation projects, loaned by Dewan Housing Finance Ltd","PM Narendra Modi to host Chinese President Xi for an informal summit","Brain Changes May Occur 30 Years Before Alzheimer’s Symptoms Appear","TCS recognised among top 50 companies in US for diversity"," Facebook may launch its own cryptocurrency by 2020: Report","Celebrating the versatile Pankaj Kapur's birthday with his memorable roles","Surprise Kiwi selection Tom Blundell on brink of ODI debut in World Cup"]
x_test_tf = count_vect.transform(test_data)
x_test_tfidf = tfidf_transformer.transform(x_test_tf)
predicted = clf.predict(x_test_tfidf)

In [46]:
print(predicted)

[5 6 5 3 6 6 3 1 3 5 3 5 3 3 3 0 5 1 5 5 5 5 1 1 3 5 1 3 3 3 5 5 5 1 3 1 3
 5 6 5 1 3 1 5 5 6 3 3 1 3]


In [47]:
#Testing the code
#Decoding from numeral to category

test_cat_list = []
for x in predicted:
    if x == 0:
        test_cat_list.append('business')
    #elif x == 1:
    #    test_cat_list.append('general')
    elif x == 1:
        test_cat_list.append('entertainment')
    elif x == 5:
        test_cat_list.append('sports')
    elif x == 3:
        test_cat_list.append('politics')
    elif x == 4:
        test_cat_list.append('science')
    elif x == 2:
        test_cat_list.append('health')
    elif x == 6:
        test_cat_list.append('technology')
print(len(test_cat_list))
print(test_cat_list)

50
['sports', 'technology', 'sports', 'politics', 'technology', 'technology', 'politics', 'entertainment', 'politics', 'sports', 'politics', 'sports', 'politics', 'politics', 'politics', 'business', 'sports', 'entertainment', 'sports', 'sports', 'sports', 'sports', 'entertainment', 'entertainment', 'politics', 'sports', 'entertainment', 'politics', 'politics', 'politics', 'sports', 'sports', 'sports', 'entertainment', 'politics', 'entertainment', 'politics', 'sports', 'technology', 'sports', 'entertainment', 'politics', 'entertainment', 'sports', 'sports', 'technology', 'politics', 'politics', 'entertainment', 'politics']


In [48]:
#import pandas as pd
#d = {'Headlines':test_data, 'Category':test_cat_list}
#print(d)
#dfd = pd.DataFrame(d)
#print(dfd)

In [49]:
#Direct Method 

import sklearn.datasets as skd
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

In [50]:
text_clf = Pipeline([('vect', TfidfVectorizer()), 
                      ('clf', MultinomialNB()) ])


In [51]:
text_clf.fit(data_list, target)
predicted = text_clf.predict(test_data)
pred_prob = text_clf.predict_proba(test_data)

In [52]:
from sklearn import metrics
from sklearn.metrics import accuracy_score
import numpy as np

In [53]:
#predicted
pred_prob 

array([[0.07734419, 0.17729162, 0.0854083 , 0.18380734, 0.09059802,
        0.2215564 , 0.16399413],
       [0.09052773, 0.24349517, 0.07013046, 0.07347176, 0.03232325,
        0.16605251, 0.32399912],
       [0.17951748, 0.11121204, 0.06465152, 0.16405615, 0.05043195,
        0.22618652, 0.20394435],
       [0.07450389, 0.13579163, 0.05653662, 0.38965773, 0.04659075,
        0.13725791, 0.15966146],
       [0.08073169, 0.10233436, 0.06082661, 0.15580052, 0.05546088,
        0.11504927, 0.42979667],
       [0.03618684, 0.07423483, 0.01960071, 0.04210807, 0.02191607,
        0.09077435, 0.71517913],
       [0.05115332, 0.17734598, 0.0406673 , 0.48703561, 0.04251604,
        0.1317073 , 0.06957445],
       [0.05802789, 0.42705533, 0.04596608, 0.12563274, 0.05568783,
        0.20590982, 0.08172031],
       [0.11214442, 0.11316225, 0.07435414, 0.26433875, 0.08555993,
        0.20583486, 0.14460566],
       [0.06604014, 0.14227406, 0.06435977, 0.13910095, 0.05068464,
        0.43785197, 0.0

In [54]:
#print(type(pred_prob))
#print(len (pred_prob))
#print (pred_prob[0])
#print(np.amax(pred_prob[0]))
prob_list =[]
for i in range(len(pred_prob)):
    prob_list.append(np.amax(pred_prob[i]))
print (len(prob_list))

50


In [55]:
d = {'Headlines':test_data, 'Category':test_cat_list, 'Probability':prob_list}
#print(d)
dfd = pd.DataFrame(d)
print(type(dfd))

<class 'pandas.core.frame.DataFrame'>


In [56]:
#fp = open('analysis.txt', 'w')
#fp.write(dfd)
#fp.close()
#np.savetxt(r'./analysis.txt', dfd.values, fmt='%s')
ds = dfd.applymap(str)
print(type(ds))
ds.to_csv('/mnt/h/workSpace/news-project/analysis.csv')
np.savetxt(r'./analysis.txt', ds.values, fmt='%s',encoding="utf-8",header="Headlines\tCategories\tProbability")

<class 'pandas.core.frame.DataFrame'>
